export const ROUTES = {
  changePassword: "/change-password",
  login: "/login",
  logout: "/logout",
  studentHome: "/student/home",
  studentClass: "/student/class",
  studentAnnouncements: "/student/announcements",
  studentHomework: "/student/homework",
  studentKnowledge: "/student/knowledge",
  studentPractice: "/student/practice",
  studentProfile: "/student/profile",
  teacherClasses: "/teacher/classes",
  teacherHomework: "/teacher/homework",
  teacherAnnouncements: "/teacher/announcements",
  teacherStatus: "/teacher/status",
  teacherProfile: "/teacher/profile",
} as const;
